colors = Deck.create(name: "Colors")
shapes = Deck.create(name: "Shapes")
foods = Deck.create(name: "Foods")
marvel_comics = Deck.create(name: "Marvel Comics")

Card.create(question: "Green means..?", answer: "go", deck_id: colors.id)
Card.create(question: "The rainbow consists of red, orange, yellow, green, blue and.. ?", answer: "indigo", deck_id: colors.id)
Card.create(question: "tomatoes are most commonly...?", answer: "red", deck_id: colors.id)
Card.create(question: "If someone's feeling down, they might refer to it as feeling...?", answer: "blue", deck_id: colors.id)
Card.create(question: "the last name of Breaking Bad's Walter", answer: "white", deck_id: colors.id)

Card.create(question: "If you're really famous you get a sign on the sidewalk in hollywood. What shape is the sign?", answer: "star", deck_id: shapes.id)
Card.create(question: "Someone who is boring might be referred to as...?", answer: "square", deck_id: shapes.id)
Card.create(question: "A friendship group is sometimes called a...?", answer: "circle", deck_id: shapes.id)
Card.create(question: "What's a square that has longer sides than height called?", answer: "rectangle", deck_id: shapes.id)
Card.create(question: "what's the name of a shape that has three sides?", answer: "triangle", deck_id: shapes.id)

Card.create(question: "What fruit is shaped like a half moon?", answer: "Banana", deck_id: foods_id)
Card.create(question: "What fruit looks like the sun?", answer: "Orange", deck_id: foods_id)
Card.create(question: "What food does the Teenage Mutant Ninja Turtles eat all the time?", answer: "Pizza", deck_id: foods_id)
Card.create(question: "What food does Garfield the Cat eat all the time?", answer: "Lasagna", deck_id: foods_id)
Card.create(question: "What can Robocop eat?", answer: "Baby Food", deck_id: foods_id)

Card.create(question: "In which comic does Spider-Man acquire his black symbiote suit?", answer: "Marvel Super Heroes Secret Wars #8", deck_id: marvel_comics_id)
Card.create(question: "What is the model of the first Iron Man suit that Tony Stark created?", answer: "Mark 1 Armor", deck_id: marvel_comics_id)
Card.create(question: "Where did the Black Panther gain his degree in physics from?", answer: "Oxford University", deck_id: marvel_comics_id)
Card.create(question: "How tall is Captain America?", answer: "188cm", deck_id: marvel_comics_id)
Card.create(question: "What type of metal was infused into Wolverine's bones?", answer: "Adamantium", deck_id: marvel_comics_id)
